---
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
allow-lan: true
mode: script
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
  - https://google.com/dns-query
  - https://cloudflare.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - tls://dns.google:853
  - https://1.1.1.1/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.google.co.id"
    - "+.yahoo.com"
    - "+.yahoo.co.id"
    - "+.bing.com"
    - "+.yandex.com"
    - "+.apple.com"
    - "+.konami.com"
    - "+.garena.com"
    - "+.garena.co.id"
    - "+.garena.sg"
    - "+.mobilelegends.com"
    - "+.pubgmobile.com"
    - "+.krafton.com"
    - "+.roblox.com"
    - "+.facebook.com"
    - "+.fbcdn.net"
    - "+.instagram.com"
    - "+.tiktok.com"
    - "+.tiktokv.com"
    - "+.tiktokcdn.com"
    - "+.musical.ly"
    - "+.twitter.com"
    - "+.twimg.com"
    - "+.whatsapp.com"
    - "+.whatsapp.net"
    - "+.youtube.com"
    - "+.ytimg.com"
    - "+.googlevideo.com"
    - "+.githubusercontent.com"
  fake-ip-filter:
  - "*.lan"
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - "*.ntp.org.cn"
  - "*.openwrt.pool.ntp.org"
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - pool.ntp.org
  - ntp.ubuntu.com
  - ntp.aliyun.com
  - ntp1.aliyun.com
  - ntp2.aliyun.com
  - ntp3.aliyun.com
  - ntp4.aliyun.com
  - ntp5.aliyun.com
  - ntp6.aliyun.com
  - ntp7.aliyun.com
  - time1.aliyun.com
  - time2.aliyun.com
  - time3.aliyun.com
  - time4.aliyun.com
  - time5.aliyun.com
  - time6.aliyun.com
  - time7.aliyun.com
  - "*.time.edu.cn"
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - "+.xboxlive.com"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "+.battlenet.com.cn"
  - "+.media.dssott.com"
  - "*.mcdn.bilivideo.cn"
  - ff.dorado.sdo.com
  - "*.ff14.sdo.com"
  - "*.ffxiv.com"
  - "*.finalfantasyxiv.com"
  - "*.square-enix.com"
  - "+.nflxvideo.net"
  - stun.l.google.com
  - lens.l.google.com
  - swdist.apple.com
  - swcdn.apple.com
  - swdownload.apple.com
  - swquery.apple.com
  - swscan.apple.com
  - mesu.apple.com
  - "*.router.asus.com"
  - "+.stun.*.*.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*"
  - "+.wargaming.net"
  - "+.wowsgame.cn"
  - "+.wggames.cn"
  - "+.wotgame.cn"
  - xnotify.xboxlive.com
  - "*.*.xboxlive.com"
  - xbox.*.*.microsoft.com
  - "*.n.n.srv.nintendo.net"
  - localhost.sec.qq.com
  - msftncsi.com
  - msftconnecttest.com
  - "+.msftncsi.com"
  - "+.msftconnecttest.com"
  - "+.pool.ntp.org"
  - ntp7.*.com
  - ntp6.*.com
  - ntp5.*.com
  - ntp4.*.com
  - ntp3.*.com
  - ntp2.*.com
  - ntp1.*.com
  - ntp.*.com
  - time7.*.com
  - time6.*.com
  - time5.*.com
  - time4.*.com
  - time3.*.com
  - time2.*.com
  - time1.*.com
  - time.*.apple.com
  - time.*.edu.cn
  - time.*.gov
  - time.*.com
  - "*.home.arpa"
  - "*.local"
  - "*.test"
  - "*.localhost"
  - "*.invalid"
  - "*.example"
  - "*.localdomain"
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
proxy-providers:
  NEWGAME:
    type: file
    path: "./proxy_provider/Proxy-Game.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  NEWSOSMED:
    type: file
    path: "./proxy_provider/Proxy-Sosmed.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  NEWSTREAM:
    type: file
    path: "./proxy_provider/Proxy-Stream.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  NEWBROWSER:
    type: file
    path: "./proxy_provider/Proxy-Browser.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
proxy-groups:
- name: NEWFINAL
  type: relay
  disable-udp: false
  proxies:
  - NEW-GAME
  - NEW-SOSMED
  - NEW-STREAM
  - NEW-BROWSER
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: NEW-GAME
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - NEWGAME
  interval: '99'
- name: NEW-SOSMED
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - NEWSOSMED
  interval: '99'
- name: NEW-STREAM
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - NEWSTREAM
  interval: '99'
- name: NEW-BROWSER
  type: fallback
  disable-udp: false
  use:
  - NEWBROWSER
  url: http://www.gstatic.com/generate_204
  interval: '99'
rule-providers:
  NewBrowser:
    type: file
    behavior: domain
    path: "./rule_provider/NewBrowser.yaml"
  NewSosmed:
    type: file
    behavior: domain
    path: "./rule_provider/NewSosmed.yaml"
  NewStream:
    type: file
    behavior: domain
    path: "./rule_provider/NewStream.yaml"
  NewGame:
    type: file
    behavior: domain
    path: "./rule_provider/NewGame.yaml"
script:
  code: |
    def main(ctx, metadata):
        ruleset_action = {"NewBrowser": "NEW-BROWSER",
            "NewSosmed": "NEW-SOSMED",
            "NewStream": "NEW-STREAM",
            "NewGame": "NEW-GAME",
          }

        port = int(metadata["dst_port"])

        if metadata["network"] == "UDP":
            if port == "21,22,23,53,80,123,143,194,443,465,587,853,993,995,998,2052,2053,2082,2083,2086,2095,2096,5223,5228,5229,5230,5242,8080,8443,8880,8888,8889,9339,10001,17000,20030,20031,20443,49152,50318,50473,50458,50460,50457,50432,50455,50471,50473,50456,59234":
                ctx.log('[Script] matched QUIC traffic use newfinal')
                return "NEWFINAL"

        if metadata["dst_ip"] == "":
            metadata["dst_ip"] = ctx.resolve_ip(metadata["host"])

        port_list = [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5223, 5228, 5229, 5230, 5242, 8080, 8443, 8880, 8888, 8889, 9339, 10001,17000, 20030, 20031, 20443, 49152, 50318, 50473, 50458, 50460, 50457, 50432, 50455, 50471, 50473, 50456, 59234]
        if port not in port_list:
            ctx.log('[Script] not common port use direct')
            return "DIRECT"

        if metadata["dst_ip"] == "":
            return "NEWFINAL"

        for ruleset in ruleset_action:
            if ctx.rule_providers[ruleset].match(metadata):
                return ruleset_action[ruleset]

        code = ctx.geoip(metadata["dst_ip"])
        if code == "ID":
            ctx.log('[Script] Geoip ID')
            return "NEWFINAL"

        ctx.log('[Script] NEWFINAL')
        return "NEWFINAL"
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,NewBrowser,NEW-BROWSER
- RULE-SET,NewSosmed,NEW-SOSMED
- RULE-SET,NewStream,NEW-STREAM
- RULE-SET,NewGame,NEW-GAME
- MATCH,NEWFINAL
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
secret: '123456'
bind-address: "*"
interface-name: eth1
